const configurations: any = {
  auckland: {
    name: 'Auckland, New Zealand',
    timezone: 'Pacific/Auckland',
    locale: 'en-NZ',
    lat: -36.8485,
    lon: 174.7633,
  },
  baghdad: {
    name: 'Baghdad, Iraq',
    timezone: 'Asia/Baghdad',
    locale: 'ar-IQ',
    lat: 33.3152,
    lon: 44.3661,
  },
  bangkok: {
    name: 'Bangkok, Thailand',
    timezone: 'Asia/Bangkok',
    locale: 'th-TH',
    lat: 13.7563,
    lon: 100.5018,
  },
  beijing: {
    name: 'Beijing, China',
    timezone: 'Asia/Shanghai',
    locale: 'zh-CN',
    lat: 39.9042,
    lon: 116.4074,
  },
  berlin: {
    name: 'Berlin, Germany',
    timezone: 'Europe/Berlin',
    locale: 'de-DE',
    lat: 52.520007,
    lon: 13.404954,
  },
  cairo: {
    name: 'Cairo, Egypt',
    timezone: 'Africa/Cairo',
    locale: 'ar-EG',
    lat: 30.0444,
    lon: 31.2357,
  },
  chicago: {
    name: 'Chicago, USA',
    timezone: 'America/Chicago',
    locale: 'en-US',
    lat: 41.8781,
    lon: -87.6298,
  },
  delhi: {
    name: 'Delhi, India',
    timezone: 'Asia/Kolkata',
    locale: 'hi-IN',
    lat: 28.7041,
    lon: 77.1025,
  },
  dubai: {
    name: 'Dubai, United Arab Emirates',
    timezone: 'Asia/Dubai',
    locale: 'ar-AE',
    lat: 25.2048,
    lon: 55.2708,
  },
  dublin: {
    name: 'Dublin, Ireland',
    timezone: 'Europe/Dublin',
    locale: 'en-IE',
    lat: 53.3498,
    lon: -6.2603,
  },
  hongKong: {
    name: 'Hong Kong, China',
    timezone: 'Asia/Hong_Kong',
    locale: 'zh-HK',
    lat: 22.3193,
    lon: 114.1694,
  },
  houston: {
    name: 'Houston, USA',
    timezone: 'America/Chicago',
    locale: 'en-US',
    lat: 29.7627,
    lon: -95.3863,
  },
  istanbul: {
    name: 'Istanbul, Turkey',
    timezone: 'Europe/Istanbul',
    locale: 'tr-TR',
    lat: 41.0082,
    lon: 28.9784,
  },
  jakarta: {
    name: 'Jakarta, Indonesia',
    timezone: 'Asia/Jakarta',
    locale: 'id-ID',
    lat: -6.2146,
    lon: 106.8451,
  },
  jerusalem: {
    name: 'Jerusalem',
    timezone: 'Asia/Jerusalem',
    locale: 'he-IL',
    lat: 31.7683,
    lon: 35.2137,
  },
  kinshasa: {
    name: 'Kinshasa, DR Congo',
    timezone: 'Africa/Lagos',
    locale: 'fr-CD',
    lat: -4.4419,
    lon: 15.2663,
  },
  kyiv: {
    name: 'Kyiv, Ukraine',
    timezone: 'Europe/Kiev',
    locale: 'uk-UA',
    lat: 50.4501,
    lon: 30.5234,
  },
  lagos: {
    name: 'Lagos, Nigeria',
    timezone: 'Africa/Lagos',
    locale: 'en-NG',
    lat: 6.5244,
    lon: 3.379,
  },
  lima: {
    name: 'Lima, Peru',
    timezone: 'America/Lima',
    locale: 'es-PE',
    lat: -12.0432,
    lon: -77.0282,
  },
  london: {
    name: 'London, UK',
    timezone: 'Europe/London',
    locale: 'en-GB',
    lat: 51.5074,
    lon: -0.1278,
  },
  losAngeles: {
    name: 'Los Angeles, USA',
    timezone: 'America/Los_Angeles',
    locale: 'en-US',
    lat: 34.0522,
    lon: -118.2437,
  },
  manila: {
    name: 'Manila, Philippines',
    timezone: 'Asia/Manila',
    locale: 'en-PH',
    lat: 14.6042,
    lon: 120.9822,
  },
  mecca: {
    name: 'Mecca, Saudi Arabia',
    timezone: 'Asia/Riyadh',
    locale: 'ar-SA',
    lat: 21.4225,
    lon: 39.8262,
  },
  mexicoCity: {
    name: 'Mexico City, Mexico',
    timezone: 'America/Mexico_City',
    locale: 'es-MX',
    lat: 19.4271,
    lon: -99.1276,
  },
  montreal: {
    name: 'Montreal, Canada',
    timezone: 'America/Toronto',
    locale: 'fr-CA',
    lat: 45.5017,
    lon: -73.5673,
  },
  moscow: {
    name: 'Moscow, Russia',
    timezone: 'Europe/Moscow',
    locale: 'ru-RU',
    lat: 55.7558,
    lon: 37.6176,
  },
  mumbai: {
    name: 'Mumbai, India',
    timezone: 'Asia/Kolkata',
    locale: 'en-IN',
    lat: 19.076,
    lon: 72.8777,
  },
  newYork: {
    name: 'New York, USA',
    timezone: 'America/New_York',
    locale: 'en-US',
    lat: 40.7127,
    lon: -74.0059,
  },
  oslo: {
    name: 'Oslo, Norway',
    timezone: 'Europe/Oslo',
    locale: 'no-NO',
    lat: 59.9138,
    lon: 10.7517,
  },
  paris: {
    name: 'Paris, France',
    timezone: 'Europe/Paris',
    locale: 'fr-FR',
    lat: 48.8566,
    lon: 2.3522,
  },
  rome: {
    name: 'Rome, Italy',
    timezone: 'Europe/Rome',
    locale: 'it-IT',
    lat: 41.9028,
    lon: 12.4964,
  },
  saintPetersburg: {
    name: 'Saint Petersburg, Russia',
    timezone: 'Europe/Moscow',
    locale: 'ru-RU',
    lat: 59.9386,
    lon: 30.3141,
  },
  saoPaulo: {
    name: 'São Paulo, Brazil',
    timezone: 'America/Sao_Paulo',
    locale: 'pt-BR',
    lat: -23.5505,
    lon: -46.6333,
  },
  sanFrancisco: {
    name: 'San Francisco, USA',
    timezone: 'America/Los_Angeles',
    locale: 'en-US',
    lat: 37.7749,
    lon: -122.4194,
  },
  seoul: {
    name: 'Seoul, South Korea',
    timezone: 'Asia/Seoul',
    locale: 'ko-KR',
    lat: 37.5665,
    lon: 126.978,
  },
  shanghai: {
    name: 'Shanghai, China',
    timezone: 'Asia/Shanghai',
    locale: 'zh-CN',
    lat: 31.2304,
    lon: 121.4737,
  },
  singapore: {
    name: 'Singapore, Singapore',
    timezone: 'Asia/Singapore',
    locale: 'en-SG',
    lat: 1.3521,
    lon: 103.8198,
  },
  sydney: {
    name: 'Sydney, Australia',
    timezone: 'Australia/Sydney',
    locale: 'en-AU',
    lat: -33.8688,
    lon: 151.2195,
  },
  taipei: {
    name: 'Taipei, Taiwan',
    timezone: 'Asia/Taipei',
    locale: 'zh-TW',
    lat: 25.0329,
    lon: 121.5654,
  },
  tokyo: {
    name: 'Tokyo, Japan',
    timezone: 'Asia/Tokyo',
    locale: 'ja-JP',
    lat: 35.6895,
    lon: 139.6917,
  },
  toronto: {
    name: 'Toronto, Canada',
    timezone: 'America/Toronto',
    locale: 'en-CA',
    lat: 43.6532,
    lon: -79.3832,
  },
  tehran: {
    name: 'Tehran, Iran',
    timezone: 'Asia/Tehran',
    locale: 'fa-IR',
    lat: 35.6892,
    lon: 51.389,
  },
  vienna: {
    name: 'Vienna, Austria',
    timezone: 'Europe/Vienna',
    locale: 'de-DE',
    lat: 48.2082,
    lon: 16.3738,
  },
  washington: {
    name: 'Washington, USA',
    timezone: 'America/New_York',
    locale: 'en-US',
    lat: 38.9072,
    lon: -77.0369,
  },
}

export default configurations
