const profiles = {
  none: { timezone: '', locale: '', lat: '', lon: '' },
  baghdad: {
    name: 'Baghdad',
    timezone: 'Asia/Baghdad',
    locale: 'ar-IQ',
    lat: 33.3152,
    lon: 44.3661,
  },
  bangkok: {
    name: 'Bangkok',
    timezone: 'Asia/Bangkok',
    locale: 'th-TH',
    lat: 13.7563,
    lon: 100.5018,
  },
  berlin: {
    name: 'Berlin',

    timezone: 'Europe/Berlin',
    locale: 'de-DE',
    lat: 52.520007,
    lon: 13.404954,
  },
  cairo: {
    name: 'Cairo',
    timezone: 'Africa/Cairo',
    locale: 'ar-EG',
    lat: 30.0444,
    lon: 31.2357,
  },
  delhi: {
    name: 'Delhi',
    timezone: 'Asia/Kolkata',
    locale: 'hi-IN',
    lat: 28.7041,
    lon: 77.1025,
  },
  dubai: {
    name: 'Dubai',
    timezone: 'Asia/Dubai',
    locale: 'ar-AE',
    lat: 25.2048,
    lon: 55.2708,
  },
  hongKong: {
    name: 'Hong Kong',
    timezone: 'Asia/Hong_Kong',
    locale: 'zh-HK',
    lat: 22.3193,
    lon: 114.1694,
  },
  houston: {
    name: 'Houston',
    timezone: 'America/Chicago',
    locale: 'en-US',
    lat: 29.7627,
    lon: -95.3863,
  },
  istanbul: {
    name: 'Istanbul',
    timezone: 'Europe/Istanbul',
    locale: 'tr-TR',
    lat: 41.0082,
    lon: 28.9784,
  },
  jerusalem: {
    name: 'Jerusalem',
    timezone: 'Asia/Jerusalem',
    locale: 'he-IL',
    lat: 31.7683,
    lon: 35.2137,
  },
  kyiv: {
    name: 'Kyiv',
    timezone: 'Europe/Kiev',
    locale: 'uk-UA',
    lat: 50.4501,
    lon: 30.5234,
  },
  lagos: {
    name: 'Lagos',
    timezone: 'Africa/Lagos',
    locale: 'en-NG',
    lat: 6.5244,
    lon: 3.379,
  },
  london: {
    name: 'London',
    timezone: 'Europe/London',
    locale: 'en-GB',
    lat: 51.5074,
    lon: -0.1278,
  },
  losAngeles: {
    name: 'Los Angeles',
    timezone: 'America/Los_Angeles',
    locale: 'en-US',
    lat: 34.0522,
    lon: -118.2437,
  },
  manila: {
    name: 'Manila',
    timezone: 'Asia/Manila',
    locale: 'en-PH',
    lat: 14.6042,
    lon: 120.9822,
  },
  mecca: {
    name: 'Mecca',
    timezone: 'Asia/Riyadh',
    locale: 'ar-SA',
    lat: 21.4225,
    lon: 39.8262,
  },
  mexicoCity: {
    name: 'Mexico City',
    timezone: 'America/Mexico_City',
    locale: 'es-MX',
    lat: 19.4271,
    lon: -99.1276,
  },
  moscow: {
    name: 'Moscow',
    timezone: 'Europe/Moscow',
    locale: 'ru-RU',
    lat: 55.7558,
    lon: 37.6176,
  },
  mumbai: {
    name: 'Mumbai',
    timezone: 'Asia/Kolkata',
    locale: 'en-IN',
    lat: 19.076,
    lon: 72.8777,
  },
  newYork: {
    name: 'New York',
    timezone: 'America/New_York',
    locale: 'en-US',
    lat: 40.7127,
    lon: -74.0059,
  },
  oslo: {
    name: 'Oslo',
    timezone: 'Europe/Oslo',
    locale: 'no-NO',
    lat: 59.9138,
    lon: 10.7517,
  },
  paris: {
    name: 'Paris',
    timezone: 'Europe/Paris',
    locale: 'fr-FR',
    lat: 48.8566,
    lon: 2.3522,
  },
  rome: {
    name: 'Rome',
    timezone: 'Europe/Rome',
    locale: 'it-IT',
    lat: 41.9028,
    lon: 12.4964,
  },
  saoPaulo: {
    name: 'São Paulo',
    timezone: 'America/Sao_Paulo',
    locale: 'pt-BR',
    lat: -23.5505,
    lon: -46.6333,
  },
  sanFrancisco: {
    name: 'San Francisco',
    timezone: 'America/Los_Angeles',
    locale: 'en-US',
    lat: 37.7749,
    lon: -122.4194,
  },
  seoul: {
    name: 'Seoul',
    timezone: 'Asia/Seoul',
    locale: 'ko-KR',
    lat: 37.5665,
    lon: 126.978,
  },
  shanghai: {
    name: 'Shanghai',
    timezone: 'Asia/Shanghai',
    locale: 'zh-CN',
    lat: 31.2304,
    lon: 121.4737,
  },
  singapore: {
    name: 'Singapore',
    timezone: 'Asia/Singapore',
    locale: 'en-SG',
    lat: 1.3521,
    lon: 103.8198,
  },
  sydney: {
    name: 'Sydney',
    timezone: 'Australia/Sydney',
    locale: 'en-AU',
    lat: -33.8688,
    lon: 151.2195,
  },
  tokyo: {
    name: 'Tokyo',
    timezone: 'Asia/Tokyo',
    locale: 'ja-JP',
    lat: 35.6895,
    lon: 139.6917,
  },
  vienna: {
    name: 'Vienna',
    timezone: 'Europe/Vienna',
    locale: 'de-DE',
    lat: 48.2082,
    lon: 16.3738,
  },
  toronto: {
    name: 'Toronto',
    timezone: 'America/Toronto',
    locale: 'en-CA',
    lat: 43.6532,
    lon: -79.3832,
  },
  washington: {
    name: 'Washington',
    timezone: 'America/New_York',
    locale: 'en-US',
    lat: 38.9072,
    lon: -77.0369,
  },
}

export default profiles
